### ISSUE TITLE
[FEATURE REQUEST] paste to upload

### ISSUE THREAD

**Issue by lc-guy** [chibisafe/chibisafe#277] opened 2021-06-11 12:39 UTC
Pasting an image to upload it used to work on lolisafe, doesn't anymore on chibisafe

**Comment by Pitu** [comment] 2021-06-18 15:36
Duplicate of #119

**Comment by Pitu** [comment] 2023-06-22 06:07
As of chibisafe v5 this is possible

**Closed by Pitu** 2023-06-22 06:07 UTC
