### ISSUE TITLE
[FEATURE REQUEST] Select multiple images for the purpose of deleting, adding tags or moving to an album

### ISSUE THREAD

**Issue by rossiscool123** [chibisafe/chibisafe#507] opened 2023-11-12 22:30 UTC
**Is your feature request related to a problem? Please describe.**
As a user of xbackbone there was an option to select multiple files for the purpose of deleting, hiding from public viewing or downloading. I'd like to see something like this in Chibisafe but with some added features to move the selected files to an album or tag for easier finding in the future.

**Describe the solution you'd like**
A mass edit button that once clicked on multiple files can be selected where you can perform bulk actions like delete, hide from public viewing, moving them to an album or tagging them.

**Comment by Pitu** [comment] 2023-11-14 19:18
This is something that it's on the roadmap but with no release date yet due to time constraints.
Duplicate of #241

**Closed by Pitu** 2023-11-14 19:18 UTC
