### ISSUE TITLE
[BUG] Video thumbnails not displaying properly in uploads

### ISSUE THREAD

**Issue by mfsoup** [chibisafe/chibisafe#271] opened 2021-04-16 07:36 UTC
**Describe the bug**
I made a video of the problem: https://lolis.amatsuka.com/Bb3ra6.mp4
ffmpeg is installed,

**To Reproduce**
1. Install ffmpeg then chibisafe
2. Upload any webm/mp4 video
3. Look at uploads

**Comment by Pitu** [comment] 2021-05-02 17:56
Seems the thumbnail is there, but only the animated part. 
The way chibisafe generates thumbnails for videos consists in 2 parts. The first part is to generate a static webp image of a frame to use as a thumbnail and then to create a video for when you hover said image. From your video I can see the video part of the thumbnail is actually there, but not the static one, so the problem is most likely not ffmpeg.

Could you open the network tab or console and see if you have any errors? You'll probably find a few 404 for those thumbnails, but then again it's weird since the images right next to your video do have a thumbnail...

**Comment by mfsoup** [comment] 2021-05-03 01:12
I checked the network tab. 
I do get 404s on the video thumbnails. They have a .webp extension but they're a broken gif file like this: https://chibisafe.amatsuka.com/thumbs/4kohqf.webp

The network tab: https://chibisafe.amatsuka.com/lyn5b9.png (top two are the broken video thumbnails, bottom two are image thumbnails)

**Comment by Pitu** [comment] 2023-06-13 00:39
I'm closing this since the new version was just pushed to master.

**Closed by Pitu** 2023-06-13 00:39 UTC
