### ISSUE TITLE
[FEATURE REQUEST] Autodelete timers

### ISSUE THREAD

**Issue by AruMoon** [chibisafe/chibisafe#298] opened 2021-09-11 22:37 UTC
**Is your feature request related to a problem? Please describe.**
As being a free self-hosted files hosting service, storage on public instances fills up

**Describe the solution you'd like**
Setting to autodelete old files uploaded some time ago and/or timers for doing that without admins

**Additional context**
Autodelete files after some time examples: https://transfer.sh/ https://0x0.st/

**Comment by CyberiumShadow** [comment] 2022-03-27 12:06
Duplicate of #30

**Closed** 2024-02-10 11:12 UTC
